List<Map<String, dynamic>> marcas = [
  {"ID_MARCA": 1, "NOMBRE_MARCA": "Colgate"},
  {"ID_MARCA": 2, "NOMBRE_MARCA": "Guadalupe"},
  {"ID_MARCA": 3, "NOMBRE_MARCA": "Aromatel"},
  {"ID_MARCA": 4, "NOMBRE_MARCA": "Head & Shoulders"},
  {"ID_MARCA": 5, "NOMBRE_MARCA": "Noel"},
  {"ID_MARCA": 6, "NOMBRE_MARCA": "Bombril"},
  {"ID_MARCA": 7, "NOMBRE_MARCA": "Doritos"},
  {"ID_MARCA": 8, "NOMBRE_MARCA": "Advil"},
  {"ID_MARCA": 9, "NOMBRE_MARCA": "Fruco"},
  {"ID_MARCA": 10, "NOMBRE_MARCA": "Colombiana"},
  {"ID_MARCA": 11, "NOMBRE_MARCA": "Coca Cola"},
  {"ID_MARCA": 12, "NOMBRE_MARCA": "Natumalta"},
  {"ID_MARCA": 13, "NOMBRE_MARCA": "Pepsi"},
  {"ID_MARCA": 14, "NOMBRE_MARCA": "Quatro"},
  {"ID_MARCA": 15, "NOMBRE_MARCA": "Fanta"},
  {"ID_MARCA": 16, "NOMBRE_MARCA": "Hatsu"},
  {"ID_MARCA": 17, "NOMBRE_MARCA": "Kola Roman"},
  {"ID_MARCA": 18, "NOMBRE_MARCA": "Postobon"},
  {"ID_MARCA": 19, "NOMBRE_MARCA": "Pony Malta"},
];
