List<Map<String, dynamic>> productos = [
  {
    "ID_PRODUCTO": 1,
    "ID_TIPO_PRODUCTO": 1,
    "ID_MARCA": 4,
    "NOMBRE_PRODUCTO": "Postobón gaseosa",
    "DESCRIPCION_PRODUCTO": "Postobón 2 litros - sabor manzana.",
    "VALOR": 3000,
  },
  {
    "ID_PRODUCTO": 2,
    "ID_TIPO_PRODUCTO": 2,
    "ID_MARCA": 7,
    "NOMBRE_PRODUCTO": "Esponja de brillo",
    "DESCRIPCION_PRODUCTO": "Esponja de brillo - bombril - promoción 2x1",
    "VALOR": 400,
  },
  {
    "ID_PRODUCTO": 3,
    "ID_TIPO_PRODUCTO": 1,
    "ID_MARCA": 2,
    "NOMBRE_PRODUCTO": "Pepsi",
    "DESCRIPCION_PRODUCTO": "Gaseosa Pepsi - 1 litro.",
    "VALOR": 2700,
  },
  {
    "ID_PRODUCTO": 4,
    "ID_TIPO_PRODUCTO": 2,
    "ID_MARCA": 4,
    "NOMBRE_PRODUCTO": "Shampoo Head & Shoulders - 200mg",
    "DESCRIPCION_PRODUCTO": "Shampoo Head & Shoulders - 200 mg. Promoción 2x1",
    "VALOR": 17000,
  },
  {
    "ID_PRODUCTO": 5,
    "ID_TIPO_PRODUCTO": 4,
    "ID_MARCA": 8,
    "NOMBRE_PRODUCTO": "Paquete de doritos",
    "DESCRIPCION_PRODUCTO": "Paquete de doritos con gaseosa. Promoción 2X1.",
    "VALOR": 1550,
  },
  {
    "ID_PRODUCTO": 6,
    "ID_TIPO_PRODUCTO": 2,
    "ID_MARCA": 7,
    "NOMBRE_PRODUCTO": "Dafini",
    "DESCRIPCION_PRODUCTO": "Producto de prueba para modificaciones.",
    "VALOR": 900,
  },
  {
    "ID_PRODUCTO": 7,
    "ID_TIPO_PRODUCTO": 2,
    "ID_MARCA": 7,
    "NOMBRE_PRODUCTO": "Fabuloso",
    "DESCRIPCION_PRODUCTO": "Limpiavidrios aromatizado - Marca \"Fabuloso\".",
    "VALOR": 7500,
  },
  {
    "ID_PRODUCTO": 8,
    "ID_TIPO_PRODUCTO": 1,
    "ID_MARCA": 6,
    "NOMBRE_PRODUCTO": "Botella Quatro",
    "DESCRIPCION_PRODUCTO": "gaseosa Quatro",
    "VALOR": 1500,
  },
];
